name: iOS Build ## name of the workflow

on:
  workflow_dispatch: # To trigger manual build
  release:
    types: [published] # only run the workflow when a new release has been published
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - release/*

jobs:
  ios-build:
    name: IOS Build
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ios

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Install dependencies
        working-directory: ./
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        working-directory: ./ios
        run: pod install --repo-update

      - name: Build App
        uses: sparkfabrik/ios-build-action@v2.0.0
        with:
          upload-to-testflight: false
          increment-build-number: false
          build-pods: true
          pods-path: 'ios/Podfile'
          project-path: ios/AwesomeProject.xcodeproj
          configuration: Debug
          export-method: development
          team-id: ${{ secrets.TEAM_ID }}
          team-name: ${{ secrets.TEAM_NAME }}
